### ISSUE TITLE
offlineimap....

### ISSUE THREAD

**Issue by pseudomyne** [chocobn69/dotfiles#1]
salut, je n'ai pas trouvé d'autre moyen de te contacter.... sorry
En fait, je cherche une solution à mon problème de sync emap / Gmail / mu4e
Comme toi, j’utilise, ou plutôt j'essaie d’utiliser mu4e pour un compte gmail.
J’ai réussi à synchroniser mon INBOX avec offlineimap en local.
j’utilise ce filtre là dans .offlineimaprc :
folderfilter = lambda folder: folder in ['INBOX', 'Sent']

mais offlineimap ne «sync» pas ’Sent’. Je me dis que c’est à cause de l'encodage des caractères de
*Messages envoy&AOk-s*... 

Par contre, en local, si j’envoie un mail, mu4e bien gentil toutou
(jusque là) me met mon message dans *Messages envoy&AOk-s* (et gmail le
reçoit sur le web). tout est ok. Par contre, bizarrement, mu4e ne «jump»
pas vers le dossier mu4e ne reconnaît pas *Messages envoy&AOk-s*. Encore l'encodage ?
Pourtant j’ai la même config que toi à ce niveau :
(setq mu4e-sent-folder   "/[Gmail].Messages envoy&AOk-s")

Ce sont peut-être des problèmes indépendants, je ne sais pas. 

si tu as un moment, ptêt tu auras une idée. je sèche là…
merci de m’avoir lu, et peut-être plus !
Another french emacsist

**Comment by chocobn69** [comment]
Salut, pas de problème.

Je crois qu'il faut tu utilises un truc du genre : 

```python
nametrans = lambda folder: {'[Gmail]/Brouillons':    'drafts',
                            '[Gmail]/Messages envoy&AOk-s': 'sent',
                            '[Gmail]/Starred':   'flagged',
                            '[Gmail]/Important':   'important',
                            '[Gmail]/Corbeille':     'trash',
                            '[Gmail]/Tous les messages':  'archive',
                            }.get(folder, folder)
```
